import mongoose from 'mongoose';

const { Schema, model } = mongoose;

// Define the Room schema
const RoomSchema = new Schema(
  {
    // Unique identifier for the room (auto-generated by MongoDB)
    name: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },
    capacity: {
      type: Number,
      required: true,
      min: 1,
    },
    // Optional description for the room
    description: {
      type: String,
      trim: true,
      maxlength: 500,
    },
    // Timestamps are added automatically by Mongoose when `timestamps` option is true
  },
  {
    timestamps: true,
    // Ensure virtuals are included when converting to JSON
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Virtual field to provide a formatted creation date
RoomSchema.virtual('createdAtFormatted').get(function () {
  return this.createdAt ? this.createdAt.toISOString() : null;
});

// Indexes for faster queries
RoomSchema.index({ name: 1 });

// Export the Room model
export default model('Room', RoomSchema);